apiVersion: v1
kind: ReplicationController
metadata:
  name: codemicroservice
spec:
  replicas: 2
  selector:
    app: codemicroservice
  template:
    metadata:
      name: codemicroservice
      labels:
        app: codemicroservice
    spec:
      containers:
      - name: codemicroservice
        image: 172.18.51.9:5000/codemicroservice:v2
        ports:
        - containerPort: 8080
