apiVersion: v1
kind: ReplicationController
metadata:
  name: mailmicroservice
spec:
  replicas: 1
  selector:
    app: mailmicroservice
  template:
    metadata:
      labels:
        app: mailmicroservice
    spec:
      containers:
      - name: mailmicroservice
        image: 172.18.51.9:5000/emailmicroservice:v3
        ports:
        - containerPort: 8080
