apiVersion: v1
kind: ReplicationController
metadata:
  name: codemicroservice
spec:
  replicas: 2
  selector:
    app: codemicroservice
  template:
    metadata:
      name: codemicroservice
      labels:
        app: codemicroservice
    spec:
      containers:
      - name: codemicroservice
        image: codemicroservice:0.0.1-SNAPSHOT
        ports:
        - containerPort: 8080
