apiVersion: v1
kind: ReplicationController
metadata:
  name: usermicroservice
spec:
  replicas: 1
  selector:
    app: usermicroservice
  template:
    metadata:
      labels:
        app: usermicroservice
    spec:
      containers:
      - name: usermicroservice
        image: usermicroservice:0.0.1-SNAPSHOT
        ports:
        - containerPort: 8080
      - name: mysql
        image: mysql:5.7
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "123456" 
        volumeMounts:
        - name: mysqldata
          mountPath: "/data"
      volumes:
      - name: mysqldata
        emptyDir: {}
